Algoritmo "dolár e real"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : di binda
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : nicolas lima albuquerque
// Data atual  : 09/03/2023
Var
 R$, US$, cotação: real
 
 


Inicio
escreval("qual a cotação do dolár")
leia( cotacao)
escreval("quantos doláres você?")
leia(US$)

//processamento

R$ <- cotacao *  UR$

//saida
escreval("



Fimalgoritmo