Algoritmo "quadrado"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : di binda
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : nicolas lima albuquerque
// Data atual  : 09/03/2023
Var
 lado, area: real

Inicio
escreval("quanto mede o lado do quadrado?")
leia( lado )

//processamento

area <-  lado * lado

//saida
escreval("a area do quadrado é de: ", area  )



Fimalgoritmo