algoritmo "semnome"
// Função :
// Autor :Nicolas Lima
// Data : 02/06/2023

var

N : caractere

inicio
escreval("digite sua menção")
leia(N)

//processamento
se (N=I) OU (N=R)= verdadeiro entao
escreval("estude mais ano que vem, você foi reprovado")


SENAO
se ( N=B) OU (N=MB)=verdadeiro entao
escreval("você foi aprovado, parabéns")


FIMSE
fimalgoritmo








fimalgoritmo
