algoritmo "semnome"
// Função :
// Autor :
// Data : 02/06/2023
// Seção de Declarações 
var
numero : real
inicio
escreval(" digite um numero ente 100 e 200")
leia (numero)

//processamentoo
se (numero>100) E (numero<200) = verdadeiro entao
escreval("o ", numero, " esta entre 100 e 200")


senao
escreval("o numero ", numero, "  não esta entre 100 e 200")

fimse
fimalgoritmo


